# --- estrategia y datos ---
entry_mode: "pullback_grid"
timeframe: "1h"
symbol: "BTC/USDT"

# fees
taker_fee: 0.0002
maker_fee: 0.0002

# Grid / anchor
grid_step_atr: 0.32
grid_span_atr: 3.0
grid_anchor: "ema30"
anchor_bias_frac: 0.5     # 50% hacia el close (1.0 = sin sesgo)
grid_side: "auto"

# filtros
rsi4h_gate: 56
trend_filter: "ema200_4h"
ema200_1h_confirm: true
atrp_gate_min: 0.25
atrp_gate_max: 1.65
ban_hours: [1]

# funding (igual que el sim)
funding_gate_bps: 160
funding_interval_hours: 8
funding_default: 0.0001
# opcional: para simulado con CSV real:
# funding_csv: "./data/BTCUSDT_USDT_funding_usdm.csv"

# riesgo/protecciones
size_mode: "full_equity"
sl_atr_mult: 1.3
max_hold_bars: 16
daily_stop_R: 2.5
emerg_trade_stop_R: 1.65
trail_to_be: false

# TP único 10% del equity al abrir
target_eq_pnl_pct: 0.10

# leverage dinámico
leverage_base: 5.0
leverage_strong: 10.0
adx_strong_threshold: 25.0

# modo
trading_mode: "simulado"   # "real" para operar live en exchange
debug_signals: true
