# --- estrategia y datos ---
entry_mode: "pullback_grid"
timeframe: "1h"
symbol: "BTC/USDT"

# fees
taker_fee: 0.0002
maker_fee: 0.0002

# Grid / anchor
grid_step_atr: 0.34
grid_span_atr: 3.0
grid_anchor: "ema30"
anchor_bias_frac: 1.0     
grid_side: "auto"

# filtros
rsi4h_gate: 56
trend_filter: "ema200_4h"
ema200_1h_confirm: true
atrp_gate_min: 0.25
atrp_gate_max: 1.50
ban_hours: [1]

# pausas por shock
shock_move_threshold_pct: 7.0
shock_pause_hours: 10.0
risk:
  guards:
    shock:
      move_threshold_pct: 7.0
      pause_hours: 10.0
      message_template: "Operación temporalmente suspendida por {hours} horas debido a volatilidad extrema (Δ24h={delta_pct:.2f}%, rango24h={range_pct:.2f}%). Se detectó una pérdida previa; se reanudará automáticamente al finalizar la pausa o con el comando /reanudar."

# funding (igual que el sim)
funding_gate_bps: 160
funding_interval_hours: 8
funding_default: 0.0001
# opcional: para simulado con CSV real:
# funding_csv: "./data/BTCUSDT_USDT_funding_usdm.csv"

# riesgo/protecciones
size_mode: "full_equity"
sl_atr_mult: 1.3
max_hold_bars: 15
daily_stop_R: 2.5
emerg_trade_stop_R: 1.8
trail_to_be: false

# SL global como % del equity al abrir (decimal). 0.05 = 5%
sl_eq_pct: 0.05
# Compatibilidad (clave anterior):
# stop_eq_pnl_pct: 0.05

# TP único 10% del equity al abrir
target_eq_pnl_pct: 0.10

# Overrides de TP por apalancamiento (si está, tiene prioridad)
# valores como decimales (0.10 = 10%). Podés cambiarlos en runtime con 'tp xN %'
tp_eq_pct_by_leverage:
  "5": 0.10
  "10": 0.10

# leverage dinámico
leverage_base: 5.0
leverage_strong: 10.0
adx_strong_threshold: 25.0

# modo
trading_mode: "simulado"   # "real" para operar live en exchange
start_equity: 1000.0
debug_signals: true

# salida opcional en horario local
output_timezone: "America/Argentina/Buenos_Aires"
