# ---------------------------------------------------
# MODO DE OPERACIÓN Y ESTRATEGIA
# ---------------------------------------------------
# Opciones: "simulado" (usa la testnet) o "real"
trading_mode: "simulado"

# Estrategia principal
entry_mode: "pullback_grid"
timeframe: "1h" # Timeframe de operación
symbol: "BTC/USDT"
balance: 1000 # Balance inicial para el modo simulado

# ---------------------------------------------------
# PARÁMETROS DE LA ESTRATEGIA GANADORA
# (Clonados del simulador del 2025-10-10)
# ---------------------------------------------------
# Apalancamiento base (para tendencias débiles)
leverage: 5

# Parámetros del Grid
grid_step_atr: 0.32
grid_span_atr: 3.0

# Filtros de Tendencia
rsi4h_gate: 56
trend_filter: "ema200_4h"
ema200_1h_confirm: true

# Filtros de Volatilidad y Horario
atrp_gate_min: 0.25
atrp_gate_max: 1.25
funding_gate_bps: 160
ban_hours: [1]

# Gestión de Riesgo y Posición
max_hold_bars: 15
daily_stop_R: 2.5
emerg_trade_stop_R: 1.65
size_mode: "full_equity"
target_eq_pnl_pct: 0.10
sl_atr_mult: 1.3
