enable: true
grid_edge_tolerance_bps: 10
regime:
  adx_min: 25
  ema200_k_atr: 0.8
  gate_bps_trend_min: 120
  gate_bps_range_max: 80
  maker_in_range: true
atr_percentile:
  lookback_bars: 1440
  step_scale_min: 0.7
  step_scale_max: 1.3
funding_bias:
  long_threshold: -0.0002
  short_threshold: 0.0002
  size_boost_pct: 10
drawdown_cap:
  lookback_days: 7
  caps:
    - { dd: 0.04, lev: 5 }
    - { dd: 0.02, lev: 7 }
    - { dd: 0.00, lev: 10 }
microstructure:
  max_spread_bps: 5
micro_burst:
  atr1m_factor: 1.8
ban_windows:
  around_funding_minutes: 10
  macro_events: []
